analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true 
  errors:
    todo: ignore
    # Ignore analyzer hints for updating pubspecs when using Future or Stream and not importing dart:async
    # Please see https://github.com/flutter/flutter/pull/24528 for details.
    sdk_version_async_exported_from_core: ignore
  exclude:
    - flutter/**
    - lib/l10n/*.dart

linter:
  rules:
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - unnecessary_const
    - unnecessary_
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors
